title: Monica Palacios Boyce, PhD # your name (or website title) here
logo: "/images/headshot-MPB.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, Deep Learning, Machine Learning, Structural Bioinformatics, Life Scientist
  <a href="https://www.linkedin.com/in/nikaboyce/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: G-ZR33EFHKZS # your Google Analytics tracking ID here
