title: Monica Palacios Boyce, PhD
logo: /images/headshot-MPB.jpg height:150px; width:150px
description: >
  Data Scientist, Deep Learning, Machine Learning, Structural
  Bioinformatics, Life Scientist <br> <br> <a
  href="https://www.linkedin.com/in/nikaboyce/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: G-ZR33EFHKZS
